// 由 tools/build-games.mjs 依据 games.config.json 自动生成 —— 请勿手改。
// 想增删游戏请编辑 games.config.json，然后运行：node tools/build-games.mjs
//
// 普通脚本（非 ES Module）：这样 index.html 直接双击以 file:// 打开也能工作，
// 数据通过 window.GAMES / window.GENRES 暴露给 js/app.js。

window.GENRES = [
  "Action",
  "Adventure",
  "Animation & Modeling",
  "Casual",
  "Design & Illustration",
  "Early Access",
  "Gacha",
  "Indie",
  "Photo Editing",
  "Racing",
  "RPG",
  "Sandbox",
  "Simulation",
  "Sports",
  "Strategy",
  "Survival",
  "Utilities"
];

window.GAMES = [
  {
    "id": 1,
    "key": "minecraft",
    "label": "Minecraft",
    "title": "Minecraft",
    "titleZh": "我的世界",
    "cover": "covers/minecraft.jpg",
    "accent": "#8fbf5f",
    "note": "",
    "dev": "Mojang Studios",
    "pub": "Xbox Game Studios",
    "genres": "Sandbox, Survival, Adventure",
    "genresZh": "沙盒, 生存, 冒险",
    "release": "18 Nov, 2011",
    "releaseZh": "2011-11-18",
    "desc": "Minecraft is a sandbox game where you explore a blocky, procedurally generated world, gather resources, craft tools, and build anything you can imagine — alone or with friends.",
    "appid": null,
    "steam": ""
  },
  {
    "id": 2,
    "key": "dance",
    "label": "冰与火之舞 A Dance of Fire and Ice",
    "title": "A Dance of Fire and Ice",
    "titleZh": "冰与火之舞 A Dance of Fire and Ice",
    "cover": "covers/dance.jpg",
    "accent": "#e6e9ee",
    "note": "",
    "dev": "7th Beat Games",
    "pub": "7th Beat Games, indienova",
    "genres": "Indie",
    "genresZh": "独立",
    "release": "24 Jan, 2019",
    "releaseZh": "2019 年 1 月 24 日",
    "desc": "A Dance of Fire and Ice is a strict rhythm game. Keep your focus as you guide two orbiting planets along a winding path without breaking their perfect equilibrium.",
    "appid": 977950,
    "steam": "https://store.steampowered.com/app/977950/"
  },
  {
    "id": 3,
    "key": "wukong",
    "label": "黑神话：悟空",
    "title": "Black Myth: Wukong",
    "titleZh": "黑神话：悟空",
    "cover": "covers/wukong.jpg",
    "accent": "#e2ddd6",
    "note": "",
    "dev": "Game Science",
    "pub": "Game Science",
    "genres": "Action, Adventure, RPG",
    "genresZh": "动作, 冒险, 角色扮演",
    "release": "19 Aug, 2024",
    "releaseZh": "2024 年 8 月 19 日",
    "desc": "Black Myth: Wukong is an action RPG rooted in Chinese mythology. You shall set out as the Destined One to venture into the challenges and marvels ahead, to uncover the obscured truth beneath the veil of a glorious legend from the past.",
    "appid": 2358720,
    "steam": "https://store.steampowered.com/app/2358720/"
  },
  {
    "id": 4,
    "key": "forza5",
    "label": "极限竞速：地平线 5",
    "title": "Forza Horizon 5",
    "titleZh": "极限竞速：地平线 5",
    "cover": "covers/forza5.jpg",
    "accent": "#dde1e8",
    "note": "",
    "dev": "Playground Games",
    "pub": "Xbox Game Studios",
    "genres": "Action, Adventure, Racing, Simulation, Sports",
    "genresZh": "动作, 冒险, 竞速, 模拟, 体育",
    "release": "8 Nov, 2021",
    "releaseZh": "2021 年 11 月 8 日",
    "desc": "Explore the vibrant open world landscapes of Mexico with limitless, fun driving action in the world’s greatest cars.",
    "appid": 1551360,
    "steam": "https://store.steampowered.com/app/1551360/"
  },
  {
    "id": 5,
    "key": "party",
    "label": "猛兽派对",
    "title": "Party Animals",
    "titleZh": "猛兽派对",
    "cover": "covers/party.jpg",
    "accent": "#eceae6",
    "note": "位于更新队列中",
    "dev": "Recreate Games",
    "pub": "Source Technology",
    "genres": "Action, Casual, Indie",
    "genresZh": "动作, 休闲, 独立",
    "release": "20 Sep, 2023",
    "releaseZh": "2023 年 9 月 20 日",
    "desc": "Fight your friends as puppies, kittens and other fuzzy creatures in PARTY ANIMALS! Paw it out with your friends remotely, or huddle together for chaotic fun on the same screen. Interact with the world under our realistic physics engine. Did I mention PUPPIES?",
    "appid": 1260320,
    "steam": "https://store.steampowered.com/app/1260320/",
    "bubble": "2"
  },
  {
    "id": 6,
    "key": "humanfall",
    "label": "人类一败涂地 / Human Fall Flat",
    "title": "Human Fall Flat",
    "titleZh": "人类一败涂地 / Human Fall Flat",
    "cover": "covers/humanfall.jpg",
    "accent": "#e4e8ee",
    "note": "",
    "dev": "No Brakes Games",
    "pub": "Curve Games",
    "genres": "Adventure, Casual, Indie, Simulation",
    "genresZh": "冒险, 休闲, 独立, 模拟",
    "release": "22 Jul, 2016",
    "releaseZh": "2016 年 7 月 22 日",
    "desc": "Human Fall Flat is a hilarious, light-hearted platformer set in floating dreamscapes that can be played solo or with up to 8 players online. Free new levels keep its vibrant community rewarded.",
    "appid": 477160,
    "steam": "https://store.steampowered.com/app/477160/"
  },
  {
    "id": 7,
    "key": "cyberpunk",
    "label": "赛博朋克 2077",
    "title": "Cyberpunk 2077",
    "titleZh": "赛博朋克 2077",
    "cover": "covers/cyberpunk.jpg",
    "accent": "#f2f2f0",
    "note": "",
    "dev": "CD PROJEKT RED",
    "pub": "CD PROJEKT RED",
    "genres": "RPG",
    "genresZh": "角色扮演",
    "release": "9 Dec, 2020",
    "releaseZh": "2020 年 12 月 9 日",
    "desc": "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.",
    "appid": 1091500,
    "steam": "https://store.steampowered.com/app/1091500/"
  },
  {
    "id": 8,
    "key": "codmw2",
    "label": "《使命召唤®：现代战争® II 2022》",
    "title": "Call of Duty®: Modern Warfare® II",
    "titleZh": "《使命召唤®：现代战争® II 2022》",
    "cover": "covers/codmw2.jpg",
    "accent": "#e0e3e0",
    "note": "",
    "dev": "Infinity Ward, Raven Software, Beenox, Treyarch, High Moon Studios, Sledgehammer Games, Demonware, Toys for Bob",
    "pub": "Activision",
    "genres": "Action",
    "genresZh": "动作",
    "release": "22 Oct, 2022",
    "releaseZh": "2022 年 10 月 22 日",
    "desc": "Call of Duty®: Modern Warfare® II drops players into an unprecedented global conflict that features the iconic Operators of Task Force 141.",
    "appid": 3595230,
    "steam": "https://store.steampowered.com/app/3595230/"
  },
  {
    "id": 9,
    "key": "bf2042",
    "label": "《战地风云™ 2042》",
    "title": "Battlefield™ 2042",
    "titleZh": "《战地风云™ 2042》",
    "cover": "covers/bf2042.jpg",
    "accent": "#e0e6ec",
    "note": "",
    "dev": "DICE",
    "pub": "Electronic Arts",
    "genres": "Action, Adventure, Casual",
    "genresZh": "动作, 冒险, 休闲",
    "release": "19 Nov, 2021",
    "releaseZh": "2021 年 11 月 19 日",
    "desc": "Battlefield™ 2042 is a first-person shooter that marks the return to the iconic all-out warfare of the franchise.",
    "appid": 1517290,
    "steam": "https://store.steampowered.com/app/1517290/"
  },
  {
    "id": 10,
    "key": "backrooms",
    "label": "Escape the Backrooms",
    "title": "Escape the Backrooms",
    "titleZh": "Escape the Backrooms",
    "cover": "covers/backrooms.jpg",
    "accent": "#ebe7dd",
    "note": "",
    "dev": "Fancy Games, Blackbird Interactive",
    "pub": "Secret Mode",
    "genres": "Action, Indie",
    "genresZh": "动作, 独立",
    "release": "23 Oct, 2025",
    "releaseZh": "2025 年 10 月 23 日",
    "desc": "Escape the Backrooms is a 1-4 player co-op horror exploration game. Traverse 30+ eerie backrooms levels while avoiding entities and other dangers. Try to escape but be warned: survival isn't guaranteed.",
    "appid": 1943950,
    "steam": "https://store.steampowered.com/app/1943950/"
  },
  {
    "id": 11,
    "key": "picopark",
    "label": "PICO PARK",
    "title": "PICO PARK",
    "titleZh": "PICO PARK",
    "cover": "covers/picopark.jpg",
    "accent": "#eae6e1",
    "note": "",
    "dev": "TECOPARK",
    "pub": "TECOPARK",
    "genres": "Action, Casual, Indie",
    "genresZh": "动作, 休闲, 独立",
    "release": "7 May, 2021",
    "releaseZh": "2021 年 5 月 7 日",
    "desc": "PICO PARK is a cooperative local/online multiplay action puzzle game for 2-8 players.",
    "appid": 1509960,
    "steam": "https://store.steampowered.com/app/1509960/"
  },
  {
    "id": 12,
    "key": "portal",
    "label": "Portal",
    "title": "Portal",
    "titleZh": "Portal",
    "cover": "covers/portal.jpg",
    "accent": "#e3e9f0",
    "note": "",
    "dev": "Valve",
    "pub": "Valve",
    "genres": "Action",
    "genresZh": "动作",
    "release": "10 Oct, 2007",
    "releaseZh": "2007 年 10 月 10 日",
    "desc": "Portal™ is a new single player game from Valve. Set in the mysterious Aperture Science Laboratories, Portal has been called one of the most innovative new games on the horizon and will offer gamers hours of unique gameplay.",
    "appid": 400,
    "steam": "https://store.steampowered.com/app/400/"
  },
  {
    "id": 13,
    "key": "portal2",
    "label": "Portal 2",
    "title": "Portal 2",
    "titleZh": "Portal 2",
    "cover": "covers/portal2.jpg",
    "accent": "#dee5ee",
    "note": "",
    "dev": "Valve",
    "pub": "Valve",
    "genres": "Action, Adventure",
    "genresZh": "动作, 冒险",
    "release": "18 Apr, 2011",
    "releaseZh": "2011 年 4 月 18 日",
    "desc": "The \"Perpetual Testing Initiative\" has been expanded to allow you to design co-op puzzles for you and your friends!",
    "appid": 620,
    "steam": "https://store.steampowered.com/app/620/"
  },
  {
    "id": 14,
    "key": "raft",
    "label": "Raft",
    "title": "Raft",
    "titleZh": "Raft",
    "cover": "covers/raft.jpg",
    "accent": "#dfe8ea",
    "note": "",
    "dev": "Redbeet Interactive",
    "pub": "Axolot Games",
    "genres": "Adventure, Indie, Simulation",
    "genresZh": "冒险, 独立, 模拟",
    "release": "20 Jun, 2022",
    "releaseZh": "2022 年 6 月 20 日",
    "desc": "Raft™ throws you and your friends into an epic oceanic adventure! Alone or together, players battle to survive a perilous voyage across a vast sea! Gather debris, scavenge reefs and build your own floating home, but be wary of the man-eating sharks!",
    "appid": 648800,
    "steam": "https://store.steampowered.com/app/648800/",
    "bubble": "2"
  },
  {
    "id": 15,
    "key": "repo",
    "label": "R.E.P.O.",
    "title": "R.E.P.O.",
    "titleZh": "R.E.P.O.",
    "cover": "covers/repo.jpg",
    "accent": "#eee6e6",
    "note": "",
    "dev": "semiwork",
    "pub": "semiwork",
    "genres": "Action, Early Access",
    "genresZh": "动作, 抢先体验",
    "release": "26 Feb, 2025",
    "releaseZh": "2025 年 2 月 26 日",
    "desc": "An online co-op horror game with up to 6 players. Locate valuable, fully physics-based objects and handle them with care as you retrieve and extract to satisfy your creator's desires.",
    "appid": 3241660,
    "steam": "https://store.steampowered.com/app/3241660/",
    "bubble": "2"
  },
  {
    "id": 16,
    "key": "seaoftheives",
    "label": "Sea of Thieves",
    "title": "Sea of Thieves: 2026 Edition",
    "titleZh": "Sea of Thieves: 2026 Edition",
    "cover": "covers/seaoftheives.jpg",
    "accent": "#dde9e4",
    "note": "",
    "dev": "Rare Ltd",
    "pub": "Xbox Game Studios",
    "genres": "Action, Adventure",
    "genresZh": "动作, 冒险",
    "release": "3 Jun, 2020",
    "releaseZh": "2020 年 6 月 3 日",
    "desc": "Sea of Thieves is a smash-hit pirate adventure game, offering the quintessential pirate experience of plundering lost treasures, intense battles, vanquishing sea monsters and more. Dive in with this revised edition of the game, which includes access to digital bonus media.",
    "appid": 1172620,
    "steam": "https://store.steampowered.com/app/1172620/"
  },
  {
    "id": 17,
    "key": "wallpaper",
    "label": "Wallpaper Engine：壁纸引擎",
    "title": "Wallpaper Engine",
    "titleZh": "Wallpaper Engine：壁纸引擎",
    "cover": "covers/wallpaper.jpg",
    "accent": "#e2e6ef",
    "note": "",
    "dev": "Wallpaper Engine Team",
    "pub": "Wallpaper Engine Team",
    "genres": "Casual, Indie, Animation & Modeling, Design & Illustration, Photo Editing, Utilities",
    "genresZh": "休闲, 独立, 动画制作和建模, 设计和插画, 照片编辑, 实用工具",
    "release": "16 Nov, 2018",
    "releaseZh": "2018 年 11 月 16 日",
    "desc": "Use stunning live wallpapers on your desktop. Animate your own images to create new wallpapers or import videos/websites and share them on the Steam Workshop!",
    "appid": 431960,
    "steam": "https://store.steampowered.com/app/431960/"
  },
  {
    "id": 18,
    "key": "wrc7",
    "label": "WRC 7",
    "title": "WRC 7 FIA World Rally Championship",
    "titleZh": "WRC 7 FIA World Rally Championship",
    "cover": "covers/wrc7.jpg",
    "accent": "#edeae0",
    "note": "",
    "dev": "KT Racing",
    "pub": "Nacon",
    "genres": "Racing",
    "genresZh": "竞速",
    "release": "15 Sep, 2017",
    "releaseZh": "2017 年 9 月 15 日",
    "desc": "Take on all the challenges of the 2017 World Rally Championship: the official cars and drivers, 13 countries, 52 Special Stages, every surface, more powerful cars, more demanding physics, longer races, and an eSports mode to keep you on the edge of your seat all year round.",
    "appid": 621830,
    "steam": "https://store.steampowered.com/app/621830/"
  },
  {
    "id": 19,
    "key": "wrcgen",
    "label": "WRC Generations - The FIA WRC Off",
    "title": "WRC Generations – The FIA WRC Official Game",
    "titleZh": "WRC Generations – The FIA WRC Official Game",
    "cover": "covers/wrcgen.jpg",
    "accent": "#ebe5df",
    "note": "",
    "dev": "KT Racing",
    "pub": "Nacon",
    "genres": "Racing, Simulation",
    "genresZh": "竞速, 模拟",
    "release": "3 Nov, 2022",
    "releaseZh": "2022 年 11 月 3 日",
    "desc": "Rise to all the challenges of the most comprehensive, realistic and demanding rally simulation ever developed. Dive into the heart of the action and drive the cars from the 2022 WRC championship, including the new hybrid models.",
    "appid": 1953520,
    "steam": "https://store.steampowered.com/app/1953520/"
  },
  {
    "id": 20,
    "key": "bluearchive",
    "label": "蔚蓝档案",
    "title": "Blue Archive",
    "titleZh": "蔚蓝档案",
    "cover": "covers/bluearchive.jpg",
    "accent": "#7fb3e8",
    "note": "",
    "dev": "NEXON Games",
    "pub": "NEXON / Yostar",
    "genres": "RPG, Gacha, Strategy",
    "genresZh": "角色扮演, 卡牌, 策略",
    "release": "4 Feb, 2021",
    "releaseZh": "2021-02-04",
    "desc": "Blue Archive is a story-driven RPG set in the academy city of Kivotos, where you lead a federal investigation club of students through tactical battles and an anime-style narrative.",
    "appid": 3557620,
    "steam": "https://store.steampowered.com/app/3557620/"
  }
];
